declare module '*.gif';
declare module '*.svg';
declare module '*.css';
declare module '*.scss';
declare module 'quill-image-resize-module-react'
declare module 'react-notifications'
declare module 'react-slick'
declare module 'react-modal'
declare module 'g-emoji'